
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekrlzeyauzfmunygvwac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcmx6ZXlhdXpmbXVueWd2d2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTE0MTIsImV4cCI6MjA1OTAyNzQxMn0.b2YrH6rKPgfhH34NQs8mV22xif0fU92Sea2TOLz2tqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
